### ISSUE TITLE
Output from find_circ error

### ISSUE THREAD

**Issue by BaluPai** [BIMSBbioinfo/ciRcus#6] opened 2016-03-08 13:51 UTC
I have been using find_circ v1.2 for generating my cirRNA result file.
But I get the following error message when using my files, whereas the test data runs are okay.
```r
circs.f <- annotateCircs(circs.bed = "C:/Users/Balu/Desktop/sample_circ_candidates.bed",
                         annot.list = annot.list,
                         assembly = "hg19")
```
```
Error in validObject(.Object) : 
  invalid class “GRanges” object: 'x@elementMetadata' is not parallel to 'x'
```
There are a few differences among the files:
 1. There is no spliced_at_end column in the new version output.
 2. Small differences in category column terms like, `PERFECT` instead of `PERFECT_EXT` etc.

The sample file is after filtering using grep.

Any help/suggestions would be appreciated.

Regards,
Balu

---
*edit (@mschilli87)*: formatting

**Comment by retaj** [comment] 2016-03-11 16:10
Dear Balu,

As you noticed, some columns were added (or changed names) in find_circ v1.2. 
It is fixed now in ciRcus, just update the package to v0.1.1

Best regards,
Petar

**Comment by BaluPai** [comment] 2016-03-14 08:13
Dear Petar,
I tried the new version over the weekend and seems to work fine. Thanks.
But another issue that I worked around is the code in annotate.R.

During the gtf2sqlite I have been getting this error:
```r
gtf2sqlite(assembly = c("hg19"),
           db.file = "hg19.sqlite")
```
```
updating AnnotationHub metadata: retrieving 1 resource
  |=============================================================================| 100%
snapshotDate(): 2016-01-25
require(“GenomicRanges”)
downloading from ‘https://annotationhub.bioconductor.org/fetch/10684’
retrieving 1 resource
  |=============================================================================| 100%
using guess work to populate seqinfo
Error in keepStandardChromosomes(gtf.gr) : 
  Cannot determine standard chromosomes, Specify species arg_
```

I have been working around by deleting the code for this part in `annotate.R`:
```r
gtf.gr <- keepStandardChromosomes(gtf.gr)
```

Thanks.

best regards,
Balu

---
*edit (@mschilli87)*: formatting

**Comment by mschilli87** [comment] 2017-02-27 11:00
@BaluPai: If this is still an issue, can you please post the output of `seqinfo` for your `GRanges`?

**Comment by mschilli87** [comment] 2017-03-14 14:21
Closing as I cannot reproduce the issue (with current version) and thus assume it was fixed in the meantime.

@BaluPai: Feel free do re-open if you still have this issue after re-installing `ciRcus`.

**Closed as completed by mschilli87** 2017-03-14 14:21 UTC
Labels: question
